name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action
        run: echo "hellow ${{ secrets.TG_BOT_TOKEN }}"
        env: # Or as an environment variable
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
